{
 "title": "Code Viewer (sp_helptext style) (Build: 2025-11-10 08:34:54 UTC)",
 "tags": [
  "code",
  "details"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ServerName" },
   { "name": "DatabaseName" },
   { "name": "SchemaName" },
   { "name": "ObjectName" }
  ]
 },
 "panels": [
  {
   "title": "Object Information",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- Object Information Section\nSELECT\n    'Object Information' AS Section,\n    s.ServerName,\n    com.DatabaseName,\n    com.SchemaName,\n    com.ObjectName,\n    com.ObjectType,\n    com.CreatedDate,\n    com.ModifiedDate,\n    com.LineCount,\n    com.CharacterCount,\n    com.DependencyCount,\n    com.LastRefreshTime\nFROM dbo.CodeObjectMetadata com\nINNER JOIN dbo.Servers s ON com.ServerID = s.ServerID\nWHERE s.ServerName = '${ServerName}'\n  AND com.DatabaseName = '${DatabaseName}'\n  AND com.SchemaName = '${SchemaName}'\n  AND com.ObjectName = '${ObjectName}';"
    }
   ]
  },
  {
   "title": "Object Definition (sp_helptext style)",
   "type": "text",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 6 },
   "options": { "content": "-- Code will be displayed here" },
   "targets": [
    {
     "rawSql": "-- Object Definition (Full Text)\nSELECT\n    oc.Definition AS CodeText\nFROM dbo.ObjectCode oc\nINNER JOIN dbo.Servers s ON oc.ServerID = s.ServerID\nWHERE s.ServerName = '${ServerName}'\n  AND oc.DatabaseName = '${DatabaseName}'\n  AND oc.SchemaName = '${SchemaName}'\n  AND oc.ObjectName = '${ObjectName}';"
    }
   ]
  },
  {
   "title": "Dependencies (What This Uses)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "-- Dependencies (What this object uses)\nSELECT\n    'Dependencies' AS Section,\n    dm.ReferencedSchemaName AS SchemaName,\n    dm.ReferencedObjectName AS ObjectName,\n    dm.ReferencedObjectType AS ObjectType\nFROM dbo.DependencyMetadata dm\nINNER JOIN dbo.Servers s ON dm.ServerID = s.ServerID\nWHERE s.ServerName = '${ServerName}'\n  AND dm.DatabaseName = '${DatabaseName}'\n  AND dm.ReferencingSchemaName = '${SchemaName}'\n  AND dm.ReferencingObjectName = '${ObjectName}'\nORDER BY dm.ReferencedObjectType, dm.ReferencedObjectName;"
    }
   ]
  },
  {
   "title": "Referenced By (What Uses This)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "-- Referenced By (What uses this object)\nSELECT\n    'Referenced By' AS Section,\n    dm.ReferencingSchemaName AS SchemaName,\n    dm.ReferencingObjectName AS ObjectName,\n    dm.ReferencingObjectType AS ObjectType\nFROM dbo.DependencyMetadata dm\nINNER JOIN dbo.Servers s ON dm.ServerID = s.ServerID\nWHERE s.ServerName = '${ServerName}'\n  AND dm.DatabaseName = '${DatabaseName}'\n  AND dm.ReferencedSchemaName = '${SchemaName}'\n  AND dm.ReferencedObjectName = '${ObjectName}'\nORDER BY dm.ReferencingObjectType, dm.ReferencingObjectName;"
    }
   ]
  }
 ]
}